-- Private rare-disease family vertical slice. Service role / trusted admin assigns roles.
do $$ begin
  create type public.family_role as enum ('family', 'steward', 'evidence_reviewer', 'admin');
exception when duplicate_object then null; end $$;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, role public.family_role not null default 'family', condition text, caregiver_role text, age_band text, timezone text, language text, help_needed text, matching_opt_in boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.circles (id uuid primary key default gen_random_uuid(), name text not null, description text, steward_id uuid references public.profiles(id), is_private boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.circle_members (circle_id uuid references public.circles(id) on delete cascade, profile_id uuid references public.profiles(id) on delete cascade, status text not null default 'pending' check (status in ('pending','active','blocked')), primary key(circle_id, profile_id));
create table if not exists public.introduction_requests (id uuid primary key default gen_random_uuid(), sender_id uuid not null references public.profiles(id), recipient_id uuid not null references public.profiles(id), note text not null, status text not null default 'pending' check (status in ('pending','accepted','declined','group_suggested')), created_at timestamptz not null default now());
create table if not exists public.circle_messages (id uuid primary key default gen_random_uuid(), circle_id uuid not null references public.circles(id) on delete cascade, sender_id uuid not null references public.profiles(id), body text not null, created_at timestamptz not null default now());
create table if not exists public.member_reports (id uuid primary key default gen_random_uuid(), reporter_id uuid not null references public.profiles(id), reported_id uuid not null references public.profiles(id), circle_id uuid references public.circles(id), reason text not null, created_at timestamptz not null default now());
create table if not exists public.private_conversations (id uuid primary key default gen_random_uuid(), introduction_id uuid unique not null references public.introduction_requests(id) on delete cascade, created_at timestamptz not null default now());
create table if not exists public.private_conversation_members (conversation_id uuid references public.private_conversations(id) on delete cascade, profile_id uuid references public.profiles(id) on delete cascade, primary key (conversation_id, profile_id));
create table if not exists public.private_messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.private_conversations(id) on delete cascade, sender_id uuid not null references public.profiles(id), body text not null, created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.circles enable row level security; alter table public.circle_members enable row level security; alter table public.introduction_requests enable row level security; alter table public.circle_messages enable row level security; alter table public.member_reports enable row level security;
alter table public.private_conversations enable row level security; alter table public.private_conversation_members enable row level security; alter table public.private_messages enable row level security;
create or replace function public.is_circle_member(target_circle uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from circle_members where circle_id=target_circle and profile_id=auth.uid() and status='active') $$;
create or replace function public.is_circle_steward(target_circle uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from circles where id=target_circle and steward_id=auth.uid()) $$;
create or replace function public.is_private_conversation_member(target_conversation uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from private_conversation_members where conversation_id=target_conversation and profile_id=auth.uid()) $$;
create or replace function public.has_family_role(target_role public.family_role) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and role in (target_role, 'admin')) $$;
create or replace function public.current_profile_role() returns public.family_role language sql stable security definer set search_path=public as $$ select role from profiles where id=auth.uid() $$;
drop policy if exists "profile owner reads own data" on public.profiles;
create policy "profile owner reads own data" on public.profiles for select to authenticated using (id=auth.uid());
drop policy if exists "new users create family profile" on public.profiles;
create policy "new users create family profile" on public.profiles for insert to authenticated with check (id=auth.uid() and role='family');
drop policy if exists "profile owner updates fields not role" on public.profiles;
create policy "profile owner updates fields not role" on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid() and role=public.current_profile_role());
drop policy if exists "profile owner deletes own data" on public.profiles;
create policy "profile owner deletes own data" on public.profiles for delete to authenticated using (id=auth.uid());
drop policy if exists "members and stewards read circles" on public.circles;
create policy "members and stewards read circles" on public.circles for select to authenticated using (is_circle_member(id) or is_circle_steward(id) or has_family_role('evidence_reviewer'));
drop policy if exists "members read membership" on public.circle_members;
create policy "members read membership" on public.circle_members for select to authenticated using (profile_id=auth.uid() or is_circle_member(circle_id) or is_circle_steward(circle_id));
drop policy if exists "families request circle access" on public.circle_members;
create policy "families request circle access" on public.circle_members for insert to authenticated with check (profile_id=auth.uid() and status='pending');
drop policy if exists "stewards moderate membership" on public.circle_members;
create policy "stewards moderate membership" on public.circle_members for update to authenticated using (is_circle_steward(circle_id));
drop policy if exists "members read messages" on public.circle_messages;
create policy "members read messages" on public.circle_messages for select to authenticated using (is_circle_member(circle_id));
drop policy if exists "members write messages" on public.circle_messages;
create policy "members write messages" on public.circle_messages for insert to authenticated with check (sender_id=auth.uid() and is_circle_member(circle_id));
drop policy if exists "participants read private introductions" on public.introduction_requests;
create policy "participants read private introductions" on public.introduction_requests for select to authenticated using (sender_id=auth.uid() or recipient_id=auth.uid());
drop policy if exists "users create own introductions" on public.introduction_requests;
create policy "users create own introductions" on public.introduction_requests for insert to authenticated with check (sender_id=auth.uid());
drop policy if exists "recipients respond to introductions" on public.introduction_requests;
create policy "recipients respond to introductions" on public.introduction_requests for update to authenticated using (recipient_id=auth.uid()) with check (recipient_id=auth.uid());
drop policy if exists "reporter files report" on public.member_reports;
create policy "reporter files report" on public.member_reports for insert to authenticated with check (reporter_id=auth.uid());
drop policy if exists "circle steward reads reports" on public.member_reports;
create policy "circle steward reads reports" on public.member_reports for select to authenticated using (is_circle_steward(circle_id));
drop policy if exists "participants read private conversations" on public.private_conversations;
create policy "participants read private conversations" on public.private_conversations for select to authenticated using (public.is_private_conversation_member(id));
drop policy if exists "participants read private conversation membership" on public.private_conversation_members;
create policy "participants read private conversation membership" on public.private_conversation_members for select to authenticated using (public.is_private_conversation_member(conversation_id));
drop policy if exists "participants read private messages" on public.private_messages;
create policy "participants read private messages" on public.private_messages for select to authenticated using (public.is_private_conversation_member(conversation_id));
drop policy if exists "participants write private messages" on public.private_messages;
create policy "participants write private messages" on public.private_messages for insert to authenticated with check (sender_id=auth.uid() and public.is_private_conversation_member(conversation_id));
create or replace function public.open_private_conversation_on_accept() returns trigger language plpgsql security definer set search_path=public as $$
declare conversation uuid;
begin
  if new.status='accepted' and old.status <> 'accepted' then
    insert into private_conversations (introduction_id) values (new.id) returning id into conversation;
    insert into private_conversation_members (conversation_id, profile_id) values (conversation, new.sender_id), (conversation, new.recipient_id) on conflict do nothing;
  end if;
  return new;
end; $$;
drop trigger if exists introduction_acceptance_opens_private_conversation on public.introduction_requests;
create trigger introduction_acceptance_opens_private_conversation after update of status on public.introduction_requests for each row execute function public.open_private_conversation_on_accept();
-- Replace the old hackathon-wide evidence read with evidence-reviewer access. Backend service role still reads the public atlas.
drop policy if exists "public read evidence" on public.evidence;
drop policy if exists "reviewers read evidence layer" on public.evidence;
create policy "reviewers read evidence layer" on public.evidence for select to authenticated using (public.has_family_role('evidence_reviewer'));
